// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRun(arg1) {
  return window['go']['app']['App']['CancelRun'](arg1);
}

export function DeletePair(arg1) {
  return window['go']['app']['App']['DeletePair'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['app']['App']['DeleteProfile'](arg1);
}

export function GetCatalog() {
  return window['go']['app']['App']['GetCatalog']();
}

export function ListCeilings() {
  return window['go']['app']['App']['ListCeilings']();
}

export function ListMounts() {
  return window['go']['app']['App']['ListMounts']();
}

export function ListPairs() {
  return window['go']['app']['App']['ListPairs']();
}

export function ListProfiles() {
  return window['go']['app']['App']['ListProfiles']();
}

export function MountFs(arg1, arg2, arg3) {
  return window['go']['app']['App']['MountFs'](arg1, arg2, arg3);
}

export function OnReady(arg1, arg2) {
  return window['go']['app']['App']['OnReady'](arg1, arg2);
}

export function OnShutdown(arg1) {
  return window['go']['app']['App']['OnShutdown'](arg1);
}

export function PreviewOperation(arg1) {
  return window['go']['app']['App']['PreviewOperation'](arg1);
}

export function RunPair(arg1, arg2) {
  return window['go']['app']['App']['RunPair'](arg1, arg2);
}

export function SavePair(arg1) {
  return window['go']['app']['App']['SavePair'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['app']['App']['SaveProfile'](arg1);
}

export function SetCeiling(arg1) {
  return window['go']['app']['App']['SetCeiling'](arg1);
}

export function StartRun(arg1, arg2) {
  return window['go']['app']['App']['StartRun'](arg1, arg2);
}

export function StatsSnapshot() {
  return window['go']['app']['App']['StatsSnapshot']();
}

export function Status() {
  return window['go']['app']['App']['Status']();
}

export function UnmountFs(arg1) {
  return window['go']['app']['App']['UnmountFs'](arg1);
}

export function Version() {
  return window['go']['app']['App']['Version']();
}
