// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {shell} from '../models';
import {app} from '../models';

export function OnReady(arg1:context.Context,arg2:shell.Runtime):Promise<void>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function Status():Promise<app.StatusDTO>;

export function Version():Promise<string>;
