// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuditView() {
  return window['go']['app']['App']['AuditView']();
}

export function CancelRun(arg1) {
  return window['go']['app']['App']['CancelRun'](arg1);
}

export function ClearHistory() {
  return window['go']['app']['App']['ClearHistory']();
}

export function DeletePair(arg1) {
  return window['go']['app']['App']['DeletePair'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['app']['App']['DeleteProfile'](arg1);
}

export function DestructiveHistory() {
  return window['go']['app']['App']['DestructiveHistory']();
}

export function ExportHistory(arg1, arg2) {
  return window['go']['app']['App']['ExportHistory'](arg1, arg2);
}

export function GetCatalog() {
  return window['go']['app']['App']['GetCatalog']();
}

export function HistoryByRemote(arg1) {
  return window['go']['app']['App']['HistoryByRemote'](arg1);
}

export function ListCeilings() {
  return window['go']['app']['App']['ListCeilings']();
}

export function ListMounts() {
  return window['go']['app']['App']['ListMounts']();
}

export function ListPairs() {
  return window['go']['app']['App']['ListPairs']();
}

export function ListProfiles() {
  return window['go']['app']['App']['ListProfiles']();
}

export function MountFs(arg1, arg2, arg3) {
  return window['go']['app']['App']['MountFs'](arg1, arg2, arg3);
}

export function OnReady(arg1, arg2) {
  return window['go']['app']['App']['OnReady'](arg1, arg2);
}

export function OnShutdown(arg1) {
  return window['go']['app']['App']['OnShutdown'](arg1);
}

export function OperationDetail(arg1) {
  return window['go']['app']['App']['OperationDetail'](arg1);
}

export function PreviewOperation(arg1) {
  return window['go']['app']['App']['PreviewOperation'](arg1);
}

export function PreviewRun(arg1) {
  return window['go']['app']['App']['PreviewRun'](arg1);
}

export function RecentHistory(arg1) {
  return window['go']['app']['App']['RecentHistory'](arg1);
}

export function RunPair(arg1, arg2) {
  return window['go']['app']['App']['RunPair'](arg1, arg2);
}

export function SavePair(arg1) {
  return window['go']['app']['App']['SavePair'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['app']['App']['SaveProfile'](arg1);
}

export function SetCeiling(arg1) {
  return window['go']['app']['App']['SetCeiling'](arg1);
}

export function StartRun(arg1, arg2) {
  return window['go']['app']['App']['StartRun'](arg1, arg2);
}

export function StatsSnapshot() {
  return window['go']['app']['App']['StatsSnapshot']();
}

export function Status() {
  return window['go']['app']['App']['Status']();
}

export function UnmountFs(arg1) {
  return window['go']['app']['App']['UnmountFs'](arg1);
}

export function Version() {
  return window['go']['app']['App']['Version']();
}
