// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCatalog() {
  return window['go']['app']['App']['GetCatalog']();
}

export function OnReady(arg1, arg2) {
  return window['go']['app']['App']['OnReady'](arg1, arg2);
}

export function OnShutdown(arg1) {
  return window['go']['app']['App']['OnShutdown'](arg1);
}

export function PreviewOperation(arg1) {
  return window['go']['app']['App']['PreviewOperation'](arg1);
}

export function StatsSnapshot() {
  return window['go']['app']['App']['StatsSnapshot']();
}

export function Status() {
  return window['go']['app']['App']['Status']();
}

export function Version() {
  return window['go']['app']['App']['Version']();
}
